2019-12-02 07:33:42,854 - remoterun - INFO - 
connect ...
2019-12-02 07:33:42,989 - remoterun - INFO - 
connection established
2019-12-02 07:33:42,991 - remoterun - INFO - 
files/folders routine
2019-12-02 07:33:43,824 - remoterun - INFO - 
files/folders routine complited
2019-12-02 07:33:43,826 - remoterun - INFO - 
Running preprocessor:
2019-12-02 07:33:43,828 - remoterun - INFO - command:
2019-12-02 07:33:43,830 - remoterun - INFO - ~/anaconda3/bin/python3 -c "import hybriddomain.gens.hs.tests.tests_gen_1d as ts; ts.run_from_remoterun()" -t /clusterhome/imaslenikov/tracer/workspace/problems/error_x -d /clusterhome/imaslenikov/tracer/workspace/settings/device_conf/devices.json -p /clusterhome/imaslenikov/tracer/workspace/settings/paths/connection.json -w /clusterhome/imaslenikov/tracer/workspace -u imaslenikov 2>&1
2019-12-02 07:33:46,947 - remoterun - INFO - 
Running solver:
2019-12-02 07:33:47,628 - remoterun - INFO - 12-02 10:33:47 produced results for t=6.90758e-310: /clusterhome/imaslenikov/tracer/workspace/problems/error_x/out/error_x-0.00000000-6.dbin

2019-12-02 07:33:51,336 - remoterun - INFO - Downloading results...
2019-12-02 07:33:51,564 - remoterun - INFO - Done!
2019-12-02 07:46:09,422 - remoterun - INFO - 
connect ...
2019-12-02 07:46:09,552 - remoterun - INFO - 
connection established
2019-12-02 07:46:09,554 - remoterun - INFO - 
files/folders routine
2019-12-02 07:46:10,317 - remoterun - INFO - 
files/folders routine complited
2019-12-02 07:46:10,319 - remoterun - INFO - 
Running preprocessor:
2019-12-02 07:46:10,321 - remoterun - INFO - command:
2019-12-02 07:46:10,323 - remoterun - INFO - ~/anaconda3/bin/python3 -c "import hybriddomain.gens.hs.tests.tests_gen_1d as ts; ts.run_from_remoterun()" -t /clusterhome/imaslenikov/tracer/workspace/problems/error_x -d /clusterhome/imaslenikov/tracer/workspace/settings/device_conf/devices.json -p /clusterhome/imaslenikov/tracer/workspace/settings/paths/connection.json -w /clusterhome/imaslenikov/tracer/workspace -u imaslenikov 2>&1
2019-12-02 07:46:14,087 - remoterun - INFO - 
Running solver:
2019-12-02 07:46:15,134 - remoterun - INFO - 12-02 10:46:14 produced results for t=6.93192e-310: /clusterhome/imaslenikov/tracer/workspace/problems/error_x/out/error_x-0.00000000-6.dbin

2019-12-02 07:46:18,642 - remoterun - INFO - Downloading results...
2019-12-02 07:46:18,849 - remoterun - INFO - Done!
2019-12-02 07:46:39,375 - remoterun - INFO - 
connect ...
2019-12-02 07:46:39,483 - remoterun - INFO - 
connection established
2019-12-02 07:46:39,484 - remoterun - INFO - 
files/folders routine
2019-12-02 07:46:40,223 - remoterun - INFO - 
files/folders routine complited
2019-12-02 07:46:40,225 - remoterun - INFO - 
Running preprocessor:
2019-12-02 07:46:40,227 - remoterun - INFO - command:
2019-12-02 07:46:40,229 - remoterun - INFO - ~/anaconda3/bin/python3 -c "import hybriddomain.gens.hs.tests.tests_gen_1d as ts; ts.run_from_remoterun()" -t /clusterhome/imaslenikov/tracer/workspace/problems/error_x -d /clusterhome/imaslenikov/tracer/workspace/settings/device_conf/devices.json -p /clusterhome/imaslenikov/tracer/workspace/settings/paths/connection.json -w /clusterhome/imaslenikov/tracer/workspace -u imaslenikov 2>&1
2019-12-02 07:46:43,321 - remoterun - INFO - 
Running solver:
2019-12-02 07:46:43,832 - remoterun - INFO - 12-02 10:46:43 produced results for t=6.90122e-310: /clusterhome/imaslenikov/tracer/workspace/problems/error_x/out/error_x-0.00000000-6.dbin

2019-12-02 07:46:47,216 - remoterun - INFO - Downloading results...
2019-12-02 07:46:47,415 - remoterun - INFO - Done!
