2019-12-12 06:51:44,793 - remoterun - INFO - 
connect ...
2019-12-12 06:51:45,095 - remoterun - INFO - 
connection established
2019-12-12 06:51:45,097 - remoterun - INFO - 
files/folders routine
2019-12-12 06:51:47,033 - remoterun - INFO - 
files/folders routine complited
2019-12-12 06:51:47,036 - remoterun - INFO - 
Running preprocessor:
2019-12-12 06:51:47,038 - remoterun - INFO - command:
2019-12-12 06:51:47,040 - remoterun - INFO - ~/anaconda3/bin/python3 -c "import hybriddomain.gens.hs.tests.tests_gen_1d as ts; ts.run()" -t /clusterhome/imaslenikov/tracer/workspace/problems/error_x -d /clusterhome/imaslenikov/tracer/workspace/settings/device_conf/devices.json -p /clusterhome/imaslenikov/tracer/workspace/settings/paths/connection.json -w /clusterhome/imaslenikov/tracer/workspace -u imaslenikov 2>&1
2019-12-12 06:52:17,641 - remoterun - INFO - 
Running solver:
2019-12-12 06:57:45,377 - remoterun - INFO - srun: error: Unable to allocate resources: Job/step already completing or completed

2019-12-12 06:57:59,303 - remoterun - INFO - Downloading results...
2019-12-12 06:57:59,359 - remoterun - INFO - Done!
2019-12-12 06:58:24,703 - remoterun - INFO - 
connect ...
2019-12-12 06:58:24,833 - remoterun - INFO - 
connection established
2019-12-12 06:58:24,835 - remoterun - INFO - 
files/folders routine
2019-12-12 06:58:26,528 - remoterun - INFO - 
files/folders routine complited
2019-12-12 06:58:26,529 - remoterun - INFO - 
Running preprocessor:
2019-12-12 06:58:26,532 - remoterun - INFO - command:
2019-12-12 06:58:26,534 - remoterun - INFO - ~/anaconda3/bin/python3 -c "import hybriddomain.gens.hs.tests.tests_gen_1d as ts; ts.run()" -t /clusterhome/imaslenikov/tracer/workspace/problems/error_x -d /clusterhome/imaslenikov/tracer/workspace/settings/device_conf/devices.json -p /clusterhome/imaslenikov/tracer/workspace/settings/paths/connection.json -w /clusterhome/imaslenikov/tracer/workspace -u imaslenikov 2>&1
2019-12-12 06:58:42,131 - remoterun - INFO - 
Running solver:
2019-12-12 06:58:43,222 - remoterun - INFO - 12-12 09:58:42 produced results for t=6.94763e-310: /clusterhome/imaslenikov/tracer/workspace/problems/error_x/out/error_x-0.00000000-6.dbin

2019-12-12 06:58:52,332 - remoterun - INFO - Downloading results...
2019-12-12 06:58:52,882 - remoterun - INFO - Done!
